version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
        - .env # Reference the .env file
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env # Reference the .env file
    ports:
      - "5050:80"

  api:
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./service/config:/app/config
      - ./service/src:/app/src
      - ./service/test:/app/test
    ports:
      - "3000:8080"
  ui:
    depends_on:
      - api
      - postgres
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - "8080:3000"